package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"

	"ads-httpproxy/pkg/logging"

	"go.uber.org/zap"
)

// ACL definition from squid.conf
type ACL struct {
	Name string
	Type string // src, dst, method, etc.
	Args []string
}

// HttpAccess rule
type AccessRule struct {
	Action string // allow, deny
	ACLs   []string
}

func main() {
	inputFile := flag.String("input", "squid.conf", "Path to squid.conf file")
	outputDir := flag.String("output", ".", "Output directory for config.yaml and policy.star")
	flag.Parse()

	// Init basic logger
	logger, _ := zap.NewDevelopment()
	logging.Logger = logger

	logger.Info("Starting migration", zap.String("input", *inputFile))

	file, err := os.Open(*inputFile)
	if err != nil {
		logger.Fatal("Failed to open input file", zap.Error(err))
	}
	defer file.Close()

	var (
		httpPort    = ":8080" // default
		acls        = make(map[string]ACL)
		accessRules = []AccessRule{}
	)

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Fields(line)
		if len(parts) == 0 {
			continue
		}

		directive := strings.ToLower(parts[0])

		switch directive {
		case "http_port":
			if len(parts) > 1 {
				// Squid handles port numbers (3128) or IP:Port.
				// For simplicity, we just take the last part if multiple args, or try to parse.
				// Assuming standard "http_port 3128"
				httpPort = ":" + parts[1]
				// If it has IP, "1.2.3.4:3128" -> perfect.
				// If just "3128" -> ":3128"
				if !strings.Contains(parts[1], ":") {
					httpPort = ":" + parts[1]
				} else {
					httpPort = parts[1]
				}
			}
		case "acl":
			if len(parts) >= 4 {
				// acl name type args...
				name := parts[1]
				typ := parts[2]
				args := parts[3:]
				acls[name] = ACL{Name: name, Type: typ, Args: args}
			}
		case "http_access":
			if len(parts) >= 3 {
				// http_access allow/deny acl1 acl2 ...
				action := parts[1]
				aclsUsed := parts[2:]
				accessRules = append(accessRules, AccessRule{Action: action, ACLs: aclsUsed})
			}
		}
	}

	if err := scanner.Err(); err != nil {
		logger.Fatal("Error reading file", zap.Error(err))
	}

	// Generate config.yaml
	generateConfig(httpPort, *outputDir)

	// Generate policy.star
	generatePolicy(acls, accessRules, *outputDir)

	logger.Info("Migration completed successfully")
}

func generateConfig(port, outDir string) {
	content := fmt.Sprintf(`# Generated by squid2ads
addr: "%s"
script_file: "./policy.star"

# Defaults
socks_addr: ":1080"
admin_api_addr: ":9090"
grpc_addr: ":9091"
enable_reuseport: true
`, port)

	err := os.WriteFile(outDir+"/config.yaml", []byte(content), 0644)
	if err != nil {
		logging.Logger.Fatal("Failed to write config.yaml", zap.Error(err))
	}
}

func generatePolicy(acls map[string]ACL, rules []AccessRule, outDir string) {
	var sb strings.Builder

	sb.WriteString(`# Generated by squid2ads
# Policy Logic based on http_access rules

def on_request(req):
    # Helper: Check CIDR
    # Starlark doesn't have built-in CIDR check easily without imports.
    # For now, we simulate with pseudo-code or rely on string matching for simplicity in this MVP.
    # Ideally, we inject a "net" module into Starlark.
    
`)

	// Define ACLs as data structures
	sb.WriteString("\n    # ACL Definitions\n")
	for _, acl := range acls {
		switch acl.Type {
		case "src":
			// src 10.0.0.0/8 ...
			sb.WriteString(fmt.Sprintf("    # ACL %s src %s\n", acl.Name, strings.Join(acl.Args, " ")))
			// We define a list for these IPs
			sb.WriteString(fmt.Sprintf("    acl_%s_ips = %s\n", acl.Name, toStarlarkList(acl.Args)))
		case "dst":
			sb.WriteString(fmt.Sprintf("    acl_%s_dsts = %s\n", acl.Name, toStarlarkList(acl.Args)))
		case "method":
			sb.WriteString(fmt.Sprintf("    acl_%s_methods = %s\n", acl.Name, toStarlarkList(acl.Args)))
		}
	}

	sb.WriteString("\n    # Rules evaluation\n")

	for _, rule := range rules {
		sb.WriteString(fmt.Sprintf("    # http_access %s %s\n", rule.Action, strings.Join(rule.ACLs, " ")))

		// Build condition: if match(acl1) and match(acl2)...
		conditions := []string{}
		for _, aclName := range rule.ACLs {
			acl, ok := acls[aclName]
			if !ok {
				if aclName == "all" {
					conditions = append(conditions, "True")
				}
				continue
			}

			// Generate check logic based on type
			switch acl.Type {
			case "src":
				// Check if req.remote (IP) is in list.
				// Naive check: string exact match or we need CIDR logic.
				// For this MVP, let's assume exact match if no CIDR logic is available yet in Starlark engine.
				// OR we stick to string containment for simple demo.
				conditions = append(conditions, fmt.Sprintf("(req.remote.split(':')[0] in acl_%s_ips)", aclName))
			case "method":
				conditions = append(conditions, fmt.Sprintf("(req.method in acl_%s_methods)", aclName))
			}
		}

		if len(conditions) > 0 {
			conditionStr := strings.Join(conditions, " and ")
			if rule.Action == "deny" {
				sb.WriteString(fmt.Sprintf("    if %s:\n        return True # Block\n", conditionStr))
			} else {
				// Allow means "do nothing" usually, unless it is a final rule?
				// In Squid, "allow" stops processing and passes.
				// In our policy, "return False" allows.
				// So if allow rule matches, we should return False
				sb.WriteString(fmt.Sprintf("    if %s:\n        return False # Allow\n", conditionStr))
			}
		}
	}

	sb.WriteString("\n    # Default policy (Implicit Deny if not allowed? Or Squid default is usually deny-all at end)\n")
	sb.WriteString("    return False # Default Action\n")

	err := os.WriteFile(outDir+"/policy.star", []byte(sb.String()), 0644)
	if err != nil {
		logging.Logger.Fatal("Failed to write policy.star", zap.Error(err))
	}
}

func toStarlarkList(args []string) string {
	quoted := []string{}
	for _, s := range args {
		quoted = append(quoted, fmt.Sprintf("\"%s\"", s))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
