# Generated by squid2ads
# Policy Logic based on http_access rules

def on_request(req):
    # Helper: Check CIDR
    # Starlark doesn't have built-in CIDR check easily without imports.
    # For now, we simulate with pseudo-code or rely on string matching for simplicity in this MVP.
    # Ideally, we inject a "net" module into Starlark.
    

    # ACL Definitions
    # ACL localnet src 10.0.0.1 192.168.1.1
    acl_localnet_ips = ["10.0.0.1", "192.168.1.1"]
    acl_unsafe_methods_methods = ["CONNECT"]

    # Rules evaluation
    # http_access deny unsafe_methods
    if (req.method in acl_unsafe_methods_methods):
        return True # Block
    # http_access allow localnet
    if (req.remote.split(':')[0] in acl_localnet_ips):
        return False # Allow
    # http_access deny all
    if True:
        return True # Block

    # Default policy (Implicit Deny if not allowed? Or Squid default is usually deny-all at end)
    return False # Default Action
